### ISSUE TITLE
Add gd2asset and gd3asset

### ISSUE THREAD

**Issue by jamesbowman** [jamesbowman/gd2-lib#8]
Add the gd2asset source here. Also gd3asset for the FT810,1,2,3.

gd3asset request:
http://gameduino2.proboards.com/thread/365/gd2asset-ft812

**Comment by automaticdai** [comment]
gd3asset?

Does this mean the new GD3 is coming out?

**Comment by lightcalamar** [comment]
http://gameduino2.proboards.com/thread/365/gd2asset-ft812?page=1&scrollTo=1417
File prep.py modified work with FT81x screen up to 1 MByte of RAM

**Comment by jamesbowman** [comment]
Done in

https://github.com/jamesbowman/gd2-asset/commit/12ed7477dbbff61fcb66fb9d7be6b6f8bdc80fb9

Closing
